cisco-en-programmability/catalyst-center-ansible-intg

playbooks/inventory_workflow_manager.yml, plugins/modules/inventory_intent.py, plugins/modules/inventory_workflow_manager.py
Sanity fix for inventory workflow manager and inventory intent
=> Inverntory workflow feature enhancement

plugins/modules/sda_fabric_devices_workflow_manager.py
Used the API 'add_control_plane_device' to add the CONTROL_NODE with the distribution protocol
=> Used the API 'add_control_plane_device' to add the CONTROL_NODE with the distribution protocol

plugins/module_utils/dnac.py
93053 - Assigning devices to an area does not have validation
=> assign device to site function common changes done

plugins/modules/site_workflow_manager.py
Update the Site module to support for replacement of membership APIs, and implement bulk site creation and upload floor map, update and delete site APIs for improved functionality with version-based routing.
=> Modifications for Site creation broken

tests/unit/modules/dnac/fixtures/site_workflow_manager.json, tests/unit/modules/dnac/test_site_workflow_manager.py
=> Changes for unit test

plugins/modules/sda_fabric_transits_workflow_manager.py
Added a function to remove the duplicates of control plane node ips.
=> Added a function to remove the duplicates of control plane node ips

plugins/modules/provision_workflow_manager.py
=> document fixed -  provision workflow manager 

plugins/modules/site_workflow_manager.py
[CSCwn15731] -> Cannot create sites; workflow needs a different hierarchy schema for 2.3.7.6
[CSCwn15932]-> Misleading message in the state: deleted for site workflow
=> Modified changes for single playbook Site workflow manager

plugins/modules/pnp_workflow_manager.py
[05696] - Unable to PnP Claim an AP, get_site_type TypeError: 'NoneType' object is not iterable
=> Pnp workflow enhancement

.circleci/config.yml, .yamllint.yml
=> converted yaml syntax errors to warning

.yamllint.yml
=> updated sanity tests to ignore yamllinting on  plugins folder

plugins/modules/site_workflow_manager.py
[CSCwn25085] --> iac2.0: sites: Backward compatibility broken, 2.3.5.3 sites config not working.
[CSCwn25842]. --> [SITE]: Error handling for "rf_model" not existing
=> Site workflow module

.github/workflows/sanity_tests_devel.yml, playbooks/sda_extranet_policies_workflow_manager.yml, plugins/modules/sda_extranet_policies_workflow_manager.py
=> Test Changes to Sanity Tests

.github/workflows/sanity_tests_devel.yml
=> testing the sanity test cases

plugins/modules/site_workflow_manager.py
[CSCwn25085] --> iac2.0: sites: Backward compatibility broken, 2.3.5.3 sites config not working.
[CSCwn25842]. --> [SITE]: Error handling for "rf_model" not existing
=> Fixed the PR-33 back to here

playbooks/inventory_workflow_manager.yml, plugins/modules/inventory_workflow_manager.py, tests/integration/ccc_inventory_management/tests/test_inventory_management.yml
Bug Fixes:
1, Update device return message and status are not correct
2, Error handling for reboot AP does not exist in inventory
3, Resync device does not exist in inventory return message is not good
have fixed the response messages
=> inventory workflow feature - bugs fixed

playbooks/sda_fabric_devices_workflow_manager.yml, plugins/modules/ise_radius_integration_workflow_manager.py, plugins/modules/sda_fabric_devices_workflow_manager.py, plugins/modules/sda_fabric_transits_workflow_manager.py
Removed the delete_fabric_device field from the playbook structure
=> Removed the delete_fabric_device field from the playbook structure

plugins/modules/sda_fabric_devices_workflow_manager.py
Validated the invalid device roles and corrected the documentation issues
1. If a site is not found in CatC, the error should be: "The provided 'fabric_name' 'Global/USA/SJC 23' is not a valid fabric site."
2. In the examples provided, tcp_mss_adjustment: 2 => should be tcp_mss_adjustment: between 500 and 1440.
3. Validated adding the SDA fabric device with an invalid device role like control plane node and edge node.
=> Validated the invalid device roles and corrected the documentation issues

plugins/modules/user_role_workflow_manager.py
The below issue is fixed
users and Role: error message when user does not exist.
- [ yes ] Bug fix
- [ no ] New feature
- [ no ] Breaking change
- [ no ] Documentation update
- [ yes ] My code follows the style guidelines of this project
- [ yes ] I have performed a self-review of my own code
- [ yes ] I have commented my code, particularly in hard-to-understand areas
- [ no ] I have made corresponding changes to the documentation
- [ yes ] My changes generate no new warnings
- [ yes ] I have added tests that prove my fix is effective or that my feature works
- [ yes ] New and existing unit tests pass locally with my changes
- [ no ] Any dependent changes have been merged and published in downstream modules
- [ yes ] All the sanity checks have been completed and the sanity test cases have …
=> User and role bug fixed

plugins/modules/template_workflow_manager.py
-- Update the documentation for the device details parameter type from list of dict to dict.
=> update the documentation and validate input params

plugins/modules/network_settings_workflow_manager.py
This PR contains the bug fix for :
Update netflow_collector (Application Visibility) has incorrect operation
[NW settings]: Update wireless_telemetry is working incorrectly
Update 'wireless_telemetry' and 'wired_data_collection' dependent on parameter 'netflow_collector'
Cannot update 'snmp_server', 'syslog_server', 'wired_data_collection', ... separately
'wireless_telemetry' and 'wired_data_collection' are set to False even though no input is provided
=> Telemetry settings bug fix

plugins/modules/site_workflow_manager.py
[CSCwn62259](http://cdetsweb-prd.cisco.com/apps/dumpcr?identifier=CSCwn62259) -->site deletion is not working
=>  Changes for delete an area bug

plugins/modules/sda_fabric_virtual_networks_workflow_manager.py
-- Update the datatype for the parameter fabric_site_location in the validate input method in fabric virtual networks workflow manager module.
=> Add the datatype for the parameter fabric_site_location.

plugins/modules/provision_workflow_manager.py
wrong param handle for primary_managed_ap_locations for wireless provision minor spelling mistake
=> bug fix in provision WLC

plugins/modules/inventory_workflow_manager.py
fixed 3 bugs, update message and updating device role
=> New inventory workflow feature

plugins/modules/inventory_workflow_manager.py
Edit device failure in "snmp_mode: AUTHNOPRIV"
have fixed the bug by adding the authpass
=> inventory bug fixed

plugins/modules/provision_workflow_manager.py
fixed 2 provision bugs
1, force provision for the WCL
2,  delete a device which is not present in the CCC
=> provision bugs fixed

playbooks/swim_workflow_manager.yml, plugins/modules/swim_workflow_manager.py
improved the error return message and updated the doc for the SAPRO devices
=> swim workflow feature - bug fix

plugins/modules/sda_fabric_devices_workflow_manager.py
Provided success message eventhough the transits are wrong when the state is deleted.
=> Provided success message eventhough the transits are wrong when the state is deleted.

plugins/modules/network_settings_workflow_manager.py
This PR contains bug fix for:  The 'ntp.servers' attribute is required to have a value of either IPv4 or IPv6 in CC-2.3.7.6
=> The 'ntp.servers' attribute is required to have a value of either IPv4 or IPv6 in CC-2.3.7.6

plugins/modules/swim_workflow_manager.py
=> backward compatibility added in SWIM

plugins/modules/template_workflow_manager.py
Added the support to  update the template_name
=> Added the support to  update the template_name

plugins/modules/inventory_workflow_manager.py
added new API to get if device is assigned to site
=> assign device to site bug fixed

plugins/modules/site_workflow_manager.py
[CSCwn77095] -->  Update image to the existing image for floor is not working.
[CSCwn69828] --> Sites Bulk create recursive hierarchies errors.
--> Modified few changes for deleting child sites
=> Updation for upload floor image

plugins/module_utils/dnac.py
CSCwn98046 - [SWIM]: Lack of information from get_site() leads to missing devices when filtering by site
=> SWIM Lack of information from get_site issue fixed

plugins/modules/sda_fabric_devices_workflow_manager.py
Added a check to copy the layer3 settings of the device when the user updates the device without layer3 settings
**How to reproduce**
Issue id - https://github.com/cisco-en-programmability/dnacenter-ansible/issues/235
1. Add a border node to the fabric (usually we will add a border node with the layer 3 settings).
2. Add a handoff to the fabric device by removing the layer 3 settings.
This PR also resolves the issue of deleting the CONTROL_PLANE_NODE when the user passes any handoff details.
Earlier it used to skip the deletion of the device due to the presence of handoffs in the playbook.
Now it will be deleted.
=> Added a check to copy the layer3 settings of the device when the user updates the device without layer3 settings

plugins/module_utils/dnac.py
Get site function code reverted to old stage
=> get_site_function_error code reverted

plugins/modules/sda_host_port_onboarding_workflow_manager.py
=> SDA Host Onboarding - regression - fixed the device unreachable issue

plugins/module_utils/dnac.py
CSCwn98046 - [SWIM]: Lack of information from get_site() leads to missing devices when filtering by site
=> Swim get_site function issue_on_offset bug fixed

plugins/modules/pnp_workflow_manager.py
=> PNP Device Documentation related changes fixed

playbooks/swim_workflow_manager.yml, plugins/modules/swim_workflow_manager.py
Added code for CCO format in list and have added device compliance for distribution and activation.
=> CCO in list - SWIM

plugins/modules/swim_workflow_manager.py
Updated the documentation for the SWIM CCO image
=> updated doc for SWIM

playbooks/swim_workflow_manager.yml, plugins/modules/swim_workflow_manager.py
=> Bug fix in SWIM Activation 

plugins/modules/device_credential_workflow_manager.py
=> Fix logging format for credential assignment

plugins/modules/sda_fabric_virtual_networks_workflow_manager.py
In this commit -
-- Fix the issue of anchored vn when fabric site is given and it is only the anchored site so will remove the anchored site and make the anchored vn as normal vn.
=> Fix the issue of Anchored vn

.github/workflows/ansible-lint.yml
=> Merge from Mainline

plugins/modules/provision_workflow_manager.py
=> bulk provision in provision workflow manager

plugins/modules/network_settings_workflow_manager.py
CSCwo26508 - [IP-pool] Deleting all ip pool with the flag cannot work
CSCwo26527 - [IP-pool] Delete IP pool does not exist return the 'changed' status.
=> Network setting delete all bug enhance bug completed

plugins/modules/network_settings_workflow_manager.py
CSCwo26508 - [IP-pool] Deleting all ip pool with the flag cannot work - output messge updated
=> Global ip pool force delete output message changed

plugins/modules/user_role_workflow_manager.py, tests/unit/modules/dnac/fixtures/user_role_workflow_manager.json, tests/unit/modules/dnac/test_user_role_workflow_manager.py
=> user and role workflow feature

plugins/modules/ise_radius_integration_workflow_manager.py, plugins/modules/sda_fabric_devices_workflow_manager.py, plugins/modules/sda_fabric_transits_workflow_manager.py
This PR includes the bug fir for:
[ISE AAA Module] - Supported states missing in the init function
[SDA Fabric Devices Module] - Supported states missing in the init function
[SDA Fabric Transits Module] - Missing supported states in the init function
=> Add Supported states missing in the init function

plugins/modules/discovery_workflow_manager.py
=> Reg: [Discovery Module] - CatC version validation missing in the main function & supported states missing

plugins/modules/discovery_workflow_manager.py
=> Added version validation. Least supported catalyst center version: 2.3.5.3

plugins/modules/user_role_workflow_manager.py, tests/unit/modules/dnac/test_user_role_workflow_manager.py
This PR contains the bug fix for following bugs:
- Create user returns fail with validation password
- Create user returns fail with message incorrect
=> Bug Fix: Create user returns fail with validation password

plugins/modules/template_workflow_manager.py
…ssing multiple template creation/updation at one time.
=> Bug Fix: Not creating all the projects, template provided in the input.

plugins/modules/template_workflow_manager.py
=> Export Project calling Non-existent SDK function bug | Delete Template Failing On Negative Testcase (Infinite Loop Issue) 

plugins/modules/template_workflow_manager.py, tests/unit/modules/dnac/fixtures/template_workflow_manager.json, tests/unit/modules/dnac/test_template_workflow_manager.py
=> Template Workflow Manager Module UT Test Cases

plugins/modules/lan_automation_workflow_manager.py
=> State based changes for lan automation workflow module

plugins/modules/lan_automation_workflow_manager.py, plugins/modules/template_workflow_manager.py
=> Bug Fix: Template workflow manager and lan automation module.

tests/unit/modules/dnac/fixtures/sda_fabric_virtual_networks_workflow_manager.json, tests/unit/modules/dnac/test_sda_fabric_sites_zones_workflow_manager.py
-- Added the UT for the module sda fabric sites zones workflow manager module.
=> Add UT for the module sda fabric sites zones workflow manager.

plugins/modules/assurance_issue_workflow_manager.py
This PR includes 
Bug fix: Issue Creation via Playbook Fails Due to Facility Validation, Works via UI
=> Bug fix: Issue Creation via Playbook Fails Due to Facility Validation, Works via UI

tests/unit/modules/dnac/fixtures/sda_fabric_sites_zones_workflow_manager.json
-- Added sda fabric sites zones workflow manager json input file for the UT
=> Added sda fabric sites zones workflow manager json input file for the UT

plugins/modules/template_workflow_manager.py, tests/unit/modules/dnac/fixtures/template_workflow_manager.json, tests/unit/modules/dnac/test_template_workflow_manager.py
=> Bug template workflow manager module: Not commiting on template upgrade.

playbooks/network_profile_wireless_workflow_manager.yml
Wireless profile YAML File fix. Removed onboarding template fields
=> Wireless profile Playbook YAML fixed

plugins/modules/tags_workflow_manager.py, tests/unit/modules/dnac/test_tags_workflow_manager.py, tests/unit/modules/dnac/test_template_workflow_manager.py
This PR removes the documentation related to batch size, as batch size control is optional and intended only for testing purposes. It also corrects the documentation authors and adds authors to the unit test files.
- [*] Documentation update
=> Documentation Update Tags workflow manager and Adding authors to UT files

plugins/modules/inventory_workflow_manager.py
-- Time zones were shown properly in the ansible galaxy documentation making it difficult to read for the end user.
Testing Done:
=> Time Zone in Maintenance is not showing correct in the galaxy

plugins/modules/site_workflow_manager.py, tests/unit/modules/dnac/fixtures/site_workflow_manager.json, tests/unit/modules/dnac/test_site_workflow_manager.py
Site Workflow Manager: Unable to Update Latitude and Longitude Using Playbook
Summary:
A bug was raised where the playbook failed to update the latitude and longitude if the existing value was None. Additionally, setting the floor number to 0 was not working correctly for versions 2.3.7.6 and above. Both issues have now been resolved.
Bug Fix:
The code was modified to handle cases where the existing latitude and longitude values are None. It now compares the requested and existing values correctly.
For the floor number, the value 0 is now converted to a string before performing the condition check, ensuring the system does not mistakenly treat it as None.
Root Cause:
The previous implementation only checked if the playbook (requested) value for latitude and longitude was None, but did not …
=> Site Workflow Manager - Latitude, Longitude and Floor 0 fixed

playbooks/tags_workflow_manager.yml, plugins/modules/tags_workflow_manager.py, tests/integration/ccc_tags_workflow_management/tests/test_tags_workflow_management.yml, tests/integration/ccc_tags_workflow_management/vars/vars_tags_workflow_management.yml, tests/unit/modules/dnac/fixtures/tags_workflow_manager.json, tests/unit/modules/dnac/test_tags_workflow_manager.py
**Added Tag Name Update Support for Tags Workflow Manager**
- Introduced the capability to update existing tag names within the Tags Workflow Manager for Catalyst Center Ansible integration.
- Updated relevant Ansible modules, playbooks to incorporate tag update logic and documentation.
- Added unit tests and integration tests for the code changes. 
N/A
Please review the tag update workflow, code comments, and documentation. Feedback on idempotency, error handling, and any missed test scenarios is appreciated.
=> Dev: Added Tag Update Support for Tags Workflow Manager 

plugins/modules/assurance_issue_workflow_manager.py, tests/unit/modules/dnac/test_assurance_issue_workflow_manager.py
Idempotent need to be implemented on Assurance issue - resolution and ignore, Current message need to be changes and failed flag need to removed.
Testing Done:
=> Assurance Issue workflow - Idempotent issue fixed for resolve and ignore

plugins/modules/template_workflow_manager.py
-- Fix the issue of template creation/updation verification.
Testing Done:
=> fix the issue of template creation verification

playbooks/network_profile_switching_workflow_manager.yml, plugins/module_utils/network_profiles.py, plugins/modules/network_profile_switching_workflow_manager.py, tests/unit/modules/dnac/fixtures/network_profile_switching_workflow_manager.json, tests/unit/modules/dnac/test_network_profile_switching_workflow_manager.py
As a part of the pull req fixed below bug and enhancement
1)  The output message need show the output with detail as processed and unprocessed
2)  Update template with existing profile bug was fixed.
3)  Delete profile functionality fixed as 
a) Delete profile based on given profile name
b) Un assign the sites from the profile.
c) Un assign the template from the profile.
d) Handling idempotent on delete profile.
Bug Fix
The output message did not clearly indicate which profiles were processed or unprocessed. This was fixed by introducing tracking variables for each profile operation.
When adding a new template to an existing profile, there was a key mismatch issue which has now been resolved by aligning with the existing key structure.
Replacing sites in an existing profile was …
=> Switch profile workflow manager - bug fixed

plugins/modules/device_credential_workflow_manager.py
**Clarified the purpose of the global_credential_details parameter to prevent misinterpretation.**
Testing Done:
=> Documentation update for global_credential_details parameter

plugins/modules/site_workflow_manager.py, tests/unit/modules/dnac/fixtures/site_workflow_manager.json, tests/unit/modules/dnac/test_site_workflow_manager.py
Site workflow manager - bug raised for the validation on the duplicate area name, getting error while duplicate site name passed. Validation added to check the duplicate in the playbook list.
Bug Fix: 
Bug raised for any duplicate site name passed in the playbook API failing and shows the error.
Root Cause (if applicable): 
Validation not added previously to check any duplicate site name passed in the playbook.
Validation added to check any duplicate item found in the list of the playbook.
Testing Done:
Test cases covered: [Mention test case …
=> Site workflow manager - Duplicate site name validation added

playbooks/inventory_workflow_manager.yml, plugins/modules/inventory_workflow_manager.py
Testing Done:
- [] Variables and secrets are handled securely (e.g., using `ansible-vault` or environment variables)
=> Inventory Workflow - Added the compare fields for verify

plugins/modules/wireless_design_workflow_manager.py
This PR Includes 2 Bugs fixes for the wireless_design_workflow_manager_module
1. [Wireless Design]: Get AttributeError: 'NoneType' object has no attribute 'get'\n" When Adding anchor group
2. [Wireless Design]: Get TypeError: argument of type 'NoneType' is not iterable When testing ap sol
--
Testing Done:
=> Wireless Design Module - 2 Bug Fixes (Nonetype error when creating anchor groups and AP profiles)

playbooks/provision_workflow_manager.yml, plugins/modules/provision_workflow_manager.py, tests/unit/modules/dnac/fixtures/provision_workflow_manager.json, tests/unit/modules/dnac/test_provision_workflow_manager.py
Bugs completed:
[Provision_app_telemetry][iac3.0]: Duplicate IPs in device_ips list prevents proper application telemetry disabling/enabling
[Provision] Blank message when assign device to site with invalid ip address
[Provision] error when using provisioning params == falseeee 
[Provision] non-handle API response when provisioned to invalid site
[Provision] Module should tell exactly problem when provision to not allowed site hierarchy
[Provision] Incorrect return message when deleted provisioned devices
[Provision_app_telemetry][iac3.0]: App telemetry enablement inconsistencies: Fails for disabled device, succeeds for unassigned/provisioned device
Bug Fix: Improved error messages and added validation in Provision, Handled duplicate ip addresses in provision telemetry
Root Cause (if …
=> Provision workflow manager bugs fixed

plugins/modules/device_configs_backup_workflow_manager.py
- [ yes] Documentation update
Parameters like family_list, type_list, series_list, and others are meant to take a list of strings, but are currently defined with type: str instead of type: list and elements: str
Testing Done:
- [ yes] My code follows the style guidelines of this project
- [ yes ] I have performed a …
=> Document changes for Device Config Backup Module

plugins/modules/provision_workflow_manager.py
1. [Provision_app_telemetry]: provision_workflow_manager does not validate required fields properly such as telemetry and device_ips
2. [Provision] Incorrect return message when provisioning == False wireless device
Bug Fix:
1. Validation added
2. Have added documentation
Root Cause (if applicable): NA
Fix Implemented: NA
Enhancement: NA
Enhancement Description: NA
Impact Area: NA
Testing Done:
=> Provision Bugs

plugins/modules/inventory_workflow_manager.py
As per bug unable to add the "THIRD PARTY DEVICE" in the inventory. Updated the example to solve the issue. 
Root Cause (if applicable): 
Error found due to random fields are passed in the playbook for each different type of device and snmp mode need to pass the proper field,  the same has been update.
Testing Done:
=> inventory workflow - fixed the third party device added in example

.github/workflows/sanity_tests.yml, .github/workflows/sanity_tests_devel.yml
Bug Fix: Updated the Python version in GitHub workflow files to `3.12` to support latest `ansible-core-2.20.0.dev0`, which now requires Python >= 3.12.
Root Cause (if applicable): `ansible-core-2.20.0.dev0` was failing in CI as Python 3.11 did not satisfy the new minimum requirement of Python >= 3.12.
Fix Implemented: Modified `python-version` from `3.11` to `3.12` in both `.github/workflows/sanity_tests.yml` and `.github/workflows/sanity_tests_devel.yml`.
Enhancement: N/A  
Enhancement Description: N/A  
Impact Area: GitHub CI workflow — specifically `sanity_tests.yml` and `sanity_tests_devel.yml`.
Testing Done:
Test cases covered: CI workflows tested with updated Python version — Ansible `devel` branch runs successfully.
This is a minimal fix to align with upstream `ansible-core` …
=> Bug Fix: Sanity Failure in Devel Version

plugins/modules/tags_workflow_manager.py
Bug Fix: Config verification mismatch between `None` and an empty string `""` for the `description` parameter in tags.
Root Cause: The module treated `None` and `""` differently during config verification, causing mismatches even though both represent no value for the tag's description in the UI.
Fix Implemented: Updated code to normalize empty string `""` values to `None` both at input parsing and while retrieving tag details from the API, ensuring consistent handling in config verification.
Impact Area:  
- `tags_workflow_manager.py` module logic for tag creation and retrieval.
- Config verification step for `description` field.
Test cases covered:
1. Create a tag without `description` — config verify passes.
2. Create a tag with `description: ""` — config verify passes.
3. Update a tag …
=> Bug Fix: Tags Workflow Manager: Normalize empty string to None for tag description to prevent config_verify mismatches

plugins/modules/assurance_issue_workflow_manager.py
As per the bug, we needed to improve the performance of command execution. Previously, tasks were executed sequentially (task by task). The requirement was to execute one task inside each item of the issue name, and then run the command accordingly.
Bug Fix:
Improved performance by modifying the logic to execute commands within each item of the issue name, instead of running tasks sequentially.
Root Cause (if applicable):
The original code was designed to process tasks one by one, which caused unnecessary delays and impacted performance.
Fix Implemented:
The execution flow was updated to run commands inside each item of the issue name. This parallelized the execution, reducing overall runtime and improving performance. …
=> Assurance Issue - Command Execution changes
