plugins/modules/provision_workflow_manager.py

Bug fix in provision workflow manager 
Problem: The provision workflow mandates the dynamic interfaces parameter incorrectly
solution have removed the mandatory terms for the dynamic interfaces

bug fix in provision workflow manager

---

plugins/modules/inventory_workflow_manager.py

Device Provisioning - version 2.3.5.3
Problem:
Error in Playbook: Reported failure to provision wired devices, even though the UI indicated success.
Log Details: DNAC logs showed an error due to a 'NoneType' object not having the expected get attribute.
Cause: The check_task_response_status function was incompatible with older API versions used for device provisioning, causing it to misinterpret API responses.
Solution:
Updated Logic for Provisioning:
New handling logic for older API versions was added in inventory_workflow_manager.py.
The function now retrieves an executionId after initiating provisioning, which is used to continuously check the provisioning status.
Status is checked in real-time, logging progress as:
Success: Logs the success message and records the device in the …

Inventory workflow workflow manager - provision in 2.3.5.3

---

plugins/modules/network_settings_workflow_manager.py

The PR contain fix for below mentioned bugs:
- Create a Global Pool with minimal configuration encountering a KeyError:  used .get() to safely check for dhcp_server_ips and dns_server_ips keys, preventing KeyError by verifying existence before type-checking.
- Unable to update network settings' message of the day: Changed the code for retain_banner_settings, now if the 
1.    retain_banner_settings is True, the type is Builtin
2.    if the retain_banner_settings is False, the type is Custom
In Addition to the above bug fixes, replaced the check_task_response_status with check_tasks_response_status, as API in check_task_response_status is going to sunset.
- [ Yes] Bug fix
- [ No] New feature
- [ No] Breaking change
- [ No] Documentation update
- [ Yes] My code follows the style guidelines …

Network settings Bug fix 

---

plugins/modules/sda_fabric_devices_workflow_manager.py

Corrected the misleading documentation and handled error for non-existing fabric site

Corrected the misleading documentation and handled error for non-existing fabric site

---

plugins/modules/accesspoint_workflow_manager.py

CSCwm83940 - IaC2.0 Access Point: Updating Power Level via Ansible is unsuccessful

Access point power_level var name update issue

---

plugins/modules/site_workflow_manager.py

Modifications for the below bug
[CSCwn27996] -- > [SITE]: The "units_of_measure" parameter not support, but playbook required

Site enhancement module changes

---

plugins/modules/site_workflow_manager.py

Modifications for the below bug
[CSCwn27996] -- > [SITE]: The "units_of_measure" parameter not support, but playbook required

changes for unit of measure bug

---

plugins/modules/swim_workflow_manager.py
tests/integration/ccc_swim_management/tests/test_swim_management.yml

New swim workflow feature

---

plugins/modules/lan_automation_workflow_manager.py

- [x ] Bug fix
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [ x] Any dependent changes have been merged and published in downstream modules
- [ x] All the sanity checks have been completed and the sanity test cases have been executed
- [x ] Tasks are idempotent (can be run multiple times …

Fix duplication issue in LAN automation workflow manager

---

plugins/modules/swim_workflow_manager.py

image activation for all the child sites devices - V2.3.7.6

swim bug fixed - image activation for all the child sites devices - V2.3.7.6

---

plugins/modules/swim_workflow_manager.py

examppple added for un-tag and tag a image

---

plugins/modules/ise_radius_integration_workflow_manager.py
plugins/modules/sda_fabric_devices_workflow_manager.py
plugins/modules/sda_fabric_transits_workflow_manager.py

Changed the check_type from string to str and integer to int in the validate_input function
1. Earlier the type in the validate_input for str is given as string.
2. Since the check for a string type in the dnac.py is 'str', I am changing it from string to str.

Changed the check_type from string to str and integer to int in the validate_input function

---

plugins/modules/device_credential_workflow_manager.py

This PR contain Bug fix : should return the error attribute instead of an unknown error

return the error attribute instead of an unknown error for invalid cli username

---

plugins/modules/network_settings_workflow_manager.py

CSCwn66555 - get_want_reserve_pool, delete_reserve_pool: IndexError: list index out of range

network_setting index out of range bug fixed

---

plugins/modules/sda_fabric_devices_workflow_manager.py

Solved the issue which deletes the devices along with the transit when we try to delete only the transits

Solved the issue which deletes the devices along with the transit when we try to delete only the transits

---

plugins/modules/sda_fabric_devices_workflow_manager.py

Solved the issue when updating the handoffs of a device when multiple devices are passed

Solved the issue when updating the handoffs of a device when multiple devices are passed

---

playbooks/sda_host_port_onboarding_workflow_manager.yml
plugins/modules/sda_host_port_onboarding_workflow_manager.py

PR Includes the fixes for the SDA Host Port Onboarding Module issues listed below:
1. Delete port-channel: "port_channel_name" needs indentifying
2. iac2.0: sda-host-port: Failed with params which are part of the module spec.
3. iac2.0: sda-host-port: Port channel shold allow to add/Remove interfaces to port channel
4. iac2.0: sda-host-port: create port channels gets into error
5. Enhancement - Wireless SSIDs remove all feature

SDA host port onboarding module - 1 Enhancement & 4 Bug fixes

---

plugins/modules/device_credential_workflow_manager.py

This PR contains bug fix for Module error: AttributeError: 'dict' object has no attribute 'append'

Fix Module error: AttributeError: 'dict' object has no attribute 'append'

---

plugins/modules/sda_fabric_devices_workflow_manager.py

Added the validation for device_roles when the device is present in the fabric site.

Added the validation for device_roles when the device is present in the fabric site.

---

plugins/module_utils/dnac.py

CSCwn85376 - [IaC2][Provision]: Site Assignment API Fails for Device Provisioning Across Multiple Sites

Provision bug for assign site to device fixed

---

plugins/modules/device_credential_workflow_manager.py

This PR contains Bug fix for :
Enter input empty but still assign any value to CLI credential

Added unset option for device credential assignment at Global site

---

plugins/modules/site_workflow_manager.py

CSCwo11889 - IaC INTG:REGR:DAILYSANITY: Sites deletion broken, trying to double delete floors.

 Site Module delete floor regression issue fixed

---

plugins/modules/pnp_workflow_manager.py

CSCwo62015 - [PnP] pnp claim cat9k device is FAILED

PNP Cat9k device mode issue manually assigned

---

plugins/modules/sda_fabric_devices_workflow_manager.py

How to reproduce - Provision a fabric device in the fabric site (CP, BN, EN) with the 'is_default_exit' as true in the border_settings.
While re-running the config again, we are getting the error saying - "The parameter 'is_default_exit' under 'layer3_settings' should not be updated for the device with IP '204.1.2.2'.",

Fixed the issue with 'is_default_exit' while re-running the same config

---

plugins/modules/pnp_workflow_manager.py

CSCwo62015 - [PnP] pnp claim cat9k device is FAILED

PNP workflow provisioned issue and mode fixed

---

plugins/modules/sda_fabric_virtual_networks_workflow_manager.py
tests/unit/modules/dnac/test_sda_fabric_virtual_networks_workflow_manager.py

-- Fix the misleading error message when IP pool is not present at given fabric site as well as in anchored site means it's not there in the Catalyst Center.
-- Also fix the issue of issue of workflow shall not exit with failure if the targeted l3 gateway is already removed from fab and reserved pool

Enhance the log message when ip pool is not reserve at this site.

---

plugins/modules/device_credential_workflow_manager.py

This PR includes bug fix for: IaC 3.0 device_credential_workflow_manager fails, Exception "Discovery' object has no attribute 'get_all_global_credentials_v2'
Bug Fix: Playbook failed on SDK 2.10.0 with exception: 'Discovery' object has no attribute 'get_all_global_credentials_v2'.
Root Cause (if applicable): get_all_global_credentials_v2 alias removed in dnacentersdk 2.10.0.
Fix Implemented: Replaced usage of alias with actual method call to restore compatibility.
Testing Done:
Test cases covered: [Mention test case IDs or brief …

Replace get_all_global_credentials_v2 for sdk 2.10.0 compatibility in device_credential_workflow_manager

---

plugins/modules/sda_host_port_onboarding_workflow_manager.py

Includes following Bug Fixes:
1. IaC3.0 sda_host_port_onboarding_workflow_manager , host on boarding not working for fabric edge in fabric zone
2. Cannot Delete just ALL wireless SSIDs mappings from a fabric site
Testing Done:

2 Bug Fixes for SDA Host Port Onboarding Module

---

plugins/modules/sda_fabric_devices_workflow_manager.py

Bug Fix: Adding a device role as `WIRELESS_CONTROLLER_NODE` for a dedicated Wireless LAN Controller (WLC) device was failing with error `Field : deviceRoles is required`.  
Root Cause: The code was always removing `WIRELESS_CONTROLLER_NODE` from `device_roles` before calling the `add_fabric_devices` API. This was correct for switches with **embedded wireless controller capabilities**  but incorrect for standalone WLC devices.  
Fix Implemented: Introduced a new flag `embedded_wireless_controller_capabilities` in `device_info` to distinguish between switches and standalone WLC devices.  
- For **standalone WLC devices**, keep `WIRELESS_CONTROLLER_NODE` in the payload.  
- For **switches with embedded wireless controller capabilities**, remove the role before sending to API if it is not …

Bug Fix: SDA Fabric Workflow Manager: Fixed error while configuring a standalone wireless controller

---

plugins/modules/inventory_workflow_manager.py

As per the bug, when a new compute device was added to the inventory with only the required fields, it threw an error because the code did not separate compute devices. This has now been fixed.
Bug Fix:
The bug was raised when adding a compute device to the inventory with only the required fields. It failed earlier, but the issue is now resolved.
Root Cause (if applicable):
The code did not properly separate compute device types, so SNMP parameters for network devices were also being added to compute devices.
Fix Implemented:
The code was updated to correctly separate compute devices and network devices, and some cognitive complexity was reduced.
Impact …

Inventory Workflow - Compute device related changes updated
